apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: ngaviniv/flask-app:v3
        volumeMounts:
          - name: db-connection
            mountPath: /opt
        ports:
        - containerPort: 5000
        volumes:
          - name: db-connection
            configMap:
              name: test-cm
